tripal.tripal_content_terms.*:
  type: config_entity
  label: 'Tripal Content Terms'
  mapping:
    id:
      type: string
      label: 'ID'
      nullable: false
    label:
      type: label
      label: 'Label'
      nullable: false
    description:
      type: string
      label: 'Description'
      nullable: false
    vocabularies:
      type: sequence
      label: 'Vocabularies'
      sequence:
        type: mapping
        mapping:
          name:
            type: string
            label: 'Vocabulary Name'
            nullable: false
          label:
            type: string
            label: 'Vocabulary Label'
            nullable: false
          url:
            type: string
            label: 'Vocabulary URL'
            nullable: false
          idSpaces:
            type: sequence
            label: 'IdSpaces used in this vocabulary'
            sequence:
              type: mapping
              mapping:
                name:
                  type: string
                  label: 'IdSpace Name'
                  nullable: false
                description:
                  type: string
                  label: 'IdSpace Description'
                  nullable: true
                urlPrefix:
                  type: string
                  label: 'IdSpace Term URL'
                  nullable: true
                isBorrowed:
                  type: boolean
                  label: 'Is Borrowed from Another Vocabulary'
                  nullable: true

          terms:
            type: sequence
            label: 'Terms'
            sequence:
              type: mapping
              mapping:
                id:
                  type: string
                  label: 'Term ID'
                  nullable: false
                name:
                  type: string
                  label: 'Term Name'
                  nullable: false
                description:
                  type: string
                  label: 'Term Definition'
                  nullable: true

field.storage.tripal_entity.*:
  type: field.storage.*.*
  label: 'Tripal Entity Field Storage'
  mapping:
    settings:
      type: field.storage_settings.*
      label: 'Tripal Field Storage Settings'
      mapping:
        max_length:
          type: integer
          label: 'Storage Maximum length'
        termIdSpace:
          type: string
          label: 'Term ID Space'
        termAccession:
          type: string
          label: 'Term Accession'
        storage_plugin_id:
          type: string
          label: 'Tripal Storage Plugin Machine Name'
        storage_plugin_settings:
          type: field.storage.tripal_entity.*.settings.storage_plugin_settings.*
          label: 'Tripal Storage-specific Settings'
                     

field.field.tripal_entity.*.*:
  type: field.field.*.*.*
  mapping:
    settings:
      type: field.settings
      mapping:
        max_delta:
          type: integer
          label: 'The maximum number of records to retreive for this field when querying'
        termIdSpace:
          type: string
          label: 'Term ID Space'
        termAccession:
          type: string
          label: 'Term Accession'

tripal.tripal_content_types.*:
   type: config_entity
   label: 'Tripal Content Types'
   mapping:
     id:
       type: string
       label: 'ID'
       nullable: false
     label:
       type: label
       label: 'Label'
       nullable: false
     description:
       type: string
       label: 'Description'
       nullable: false
     content_types:
         type: sequence
         label: 'Content Types'
         sequence:
           type: mapping
           mapping:
               label:
                 type: string
                 label: 'Label'
                 nullable: false
               term:
                 type: string
                 label: "Term ID (e.g., OBI:0100026)"
                 nullable: false
               category:
                 type: string
                 label: "Category"
                 nullable: false
               name:
                 type: string
                 label: "A machine readable content type id (a.k.a., the bundle ID or Entity Type ID)"
                 nullable: false
               help_text:
                 type: string
                 label: "Text used to describe to the end-user what this content type is used for"
                 nullable: false
               url_format:
                 type: string
                 label: "A tokenzied string for the URL of the content type. Field names in square brackets can be used as tokens."
                 nullable: true               
               title_format:
                 type: string
                 label: "A tokenzied string for the title of the content type. Field names in square brackets can be used as tokens."
                 nullable: true               
               synonyms:
                 type: sequence
                 label: "Synonyms"
                 nullable: true
                 sequence:
                    type: string
                    label: "Synonym name"
              
                    
tripal.tripal_fields.*:
   type: config_entity
   label: 'Tripal Content Types'
   mapping:
     id:
       type: string
       label: 'ID'
       nullable: false
     label:
       type: label
       label: 'Label'
       nullable: false
     description:
       type: string
       label: 'Description'
     fields:
         type: sequence
         label: 'Fields'
         sequence:
           type: mapping
           mapping:
               name:
                 type: string
                 label: 'The field name. It must '
                 nullable: false
               content_type:
                 type: string
                 label: 'The name of the content type this field should be attached to'
                 nullable: false
               label:
                 type: string
                 label: 'Label'
                 nullable: false
               type:
                 type: string
                 label: 'Type'
                 nullable: false
               description:
                 type: string
                 label: 'Description'
                 nullable: false
               cardinality:
                 type: integer
                 label: 'Cardinality'
                 nullable: false
               required:
                 type: boolean
                 label: 'Required'
                 nullable: false
               storage_settings:
                 type: mapping
                 label: 'Storage Settings'
                 mapping:
                   storage_plugin_id:
                     type: string
                     label: 'Storage Plugin ID'
                     nullable: false
                   storage_plugin_settings:
                      type: mapping
                      label: 'Storage Plugin Settings'
                   termIdSpace:
                     type: string
                     label: "Term Id Space"
                     nullable: false
                   termAccession:
                     type: string
                     label: "Term Accession"
                     nullable: false
                   max_length:
                     type: integer
                     label: "The maximum size of the field vlaue."                     
               settings:
                 type: mapping
                 label: 'Settings'
                 mapping:
                   termIdSpace:
                     type: string
                     label: "Term Id Space"
                     nullable: false
                   termAccession:
                     type: string
                     label: "Term Accession"
                     nullable: false
                   fixed_value:
                     type: string
                     label: "A fixed value for the field that cannot be changed."
                     nullable: true
               display:
                 type: mapping
                 label: 'Display'
                 mapping:
                   view:
                     type: sequence
                     label: 'View'
                     sequence:
                       type: mapping
                       mapping:
                         name:
                           type: string
                           label: 'Display'
                           nullable: false
                         region:
                           type: string
                           label: 'Region'
                           nullable: false
                         label:
                           type: string
                           label: 'Label'
                           nullable: false
                         weight:
                           type: integer
                           label: 'Weight'
                           nullable: false
                   form:
                     type: sequence
                     label: 'View'
                     sequence:
                       type: mapping
                       mapping:
                         name:
                           type: string
                           label: 'Display'
                           nullable: false
                         region:
                           type: string
                           label: 'Region'
                           nullable: false
                         label:
                           type: string
                           label: 'Label'
                           nullable: false
                         weight:
                           type: integer
                           label: 'Weight'
                           nullable: false
